server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.223.20:3306/flyway_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

  flyway:
    #是否启用
#    enabled: true
    # 可以支持多个location, 用','隔开
#    locations: classpath:db/migration
    #是否创建元数据表
    validate-on-migrate: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。
    clean-disabled: true
#    clean-on-validation-error: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用
    baseline-version: 0
    # 版本控制日志表，默认flyway_schema_history,不同系统建议修改数据
    table: flyway_schema_history
    connect-retries: 5
    fail-on-missing-locations: true
    connect-retries-interval: 120
    lock-retry-count: 50
#debug: true